### ISSUE TITLE
华为云函数报错

### ISSUE THREAD

**Issue by OKkami** [LinChiQ/NewWoZaiXiaoYuan#1]
错误代码：

{
    "errorMessage": "function entry exception, error: handler 'handler' not found in module 'index'(module 'index' has no attribute 'handler')",
    "errorType": "AttributeError"
}

错误码
FSS.4001

场景描述
找不到函数入口。

解决方案
请检查函数的执行入口和代码中的函数入口是否一致。

**Comment by LinChiQ** [comment]
适用于华为云函数的代码以及配置教程已上传，谢谢issue
