### ISSUE TITLE
登录接口失效

### ISSUE THREAD

**Issue by Alicil** [LinChiQ/NewWoZaiXiaoYuan#12]
登录接口域名已更改：https://wzxy.chaoxing.com/basicinfo/mobile/login/username

**Comment by LinChiQ** [comment]
旧登录接口依然可以使用，第一次运行程序之前需要在我在校园中更改一次密码并且点击清除缓存后，等待页面跳转到账号密码登录页面后再输入程序。
![image](https://github.com/user-attachments/assets/76ee7410-96b4-4ef1-9206-243fcc5824ba)

**Comment by Alicil** [comment]
没有修改密码入口

**Comment by Alicil** [comment]
![image](https://github.com/user-attachments/assets/aae4c1c0-18c9-4b60-95f1-bf58a2d5bfb4)
我的版本中无修改密码入口

**Comment by Alicil** [comment]
![image](https://github.com/user-attachments/assets/778ae218-7515-4901-8d5b-10ccc4f13ba8)
我使用的版本中无这个入口，所以只能找客服修改密码

**Comment by LinChiQ** [comment]
这版本没见过啊，可能学校不一样吧

**Comment by Alicil** [comment]
参考参考，写一个出来就行了
