### ISSUE TITLE
github actions 是已经不能用了吗？

### ISSUE THREAD

**Issue by Asukapipi** [LinChiQ/NewWoZaiXiaoYuan#18]
按照说明进行配置github actions工作流无法运行

**Comment by LinChiQ** [comment]
能详细描述或者提供截图吗

**Comment by Asukapipi** [comment]
更具您的有关Github Action的使用方法进行配置，在最后打卡测试步骤时，点击绿色的Run workflow按钮后，并未有成功运行工作流，仅是左上角提示已成功请求工作流运行，后续晚上10点的打卡时间仍未有任何工作流运行，已多次进行配置尝试仍无果，想请问是有什么配置方面的遗漏或者是已经停止运行github action了吗？我看到包括您和部分fork了您项目的人他们的action差不多都停止在了两周前。
<img width="1263" alt="屏幕截图 2024-12-09 121254" src="https://github.com/user-attachments/assets/d791438b-47bb-4acb-8a2c-8da62a63c6fb">

**Comment by Asukapipi** [comment]
唐完了，文章里提到默认时间10点我就没改，导致action没定时运行，但是action运行成功后只能收到server酱的微信推送，smtp邮箱投送还是收不到，已修改过多次授权码以及更换服务器端运行WoZaiXiaoYuan.py尝试后还是只有server酱的推送，想请问有什么查错的方法吗？

**Comment by LinChiQ** [comment]
action是国外服务器，国内的SMTP服务器有些无法访问（测试过163无法访问），你可以换几个试试看

**Comment by Asukapipi** [comment]
更换Gmail后可以正常接收到了，但是有可能会收到垃圾邮箱里，需要移除黑名单后才能正常接收，很棒的代码💯

**Comment by Asukapipi** [comment]
您好，在github action中添加第二名和第三名打卡用户时，更具您提供的方法在punch.yml中删除注释后添加User02，复制User02代码添加User03之后会导致action产生错误，我对比了User02和User01部分的代码发现存在不同，复制粘贴统一为User01的形式时User02和User03就都打卡成功了，以下为使用原User02代码配置时的反馈错误
<img width="498" alt="1111" src="https://github.com/user-attachments/assets/2f7e290a-b11c-4c88-a7f5-ce8578c74726" />

**Comment by LinChiQ** [comment]
统一复制user01的代码即可，user02的代码没有及时更新。
