### ISSUE TITLE
华为云函数运行报错

### ISSUE THREAD

**Issue by Echozxc** [LinChiQ/NewWoZaiXiaoYuan#6]
按步骤来的运行日志如下：2024-03-16T08:53:30Z 132730d4-9503-41c7-b16a-86b9b45f5270 ERROR function entry exception, error: failed to import module 'index'(No module named 'Crypto')
安装pycryptodome依赖后继续运行变2024-03-16T08:56:18Z 42b55f1c-0086-4786-bc90-371158bad572 ERROR function entry exception, error: module initialization error(Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cpython-39-x86_64-linux-gnu.so', Not found '_raw_ecb.abi3.so', Not found '_raw_ecb.so')
求助作者大大，这个报错如何解决？

**Comment by LinChiQ** [comment]
我在校园在更新密码加密以后需要使用到pycryptodemo，华为云函数部分所需依赖过多，你可以使用https://github.com/mudea661/daily/的仓库，他提供了Github Action的使用。

**Comment by LinChiQ** [comment]
本项目已开发GitHub action版本，本issue关闭
