### ISSUE TITLE
未找到未打卡项目

### ISSUE THREAD

**Issue by bober233** [LinChiQ/NewWoZaiXiaoYuan#8]
请问用了github的自动运行 未找到未打卡项目怎么办呢 我的是定位签到

**Comment by LinChiQ** [comment]
当前适用于每日打卡里的归寝打卡，可以携带具体的我在校园对应页面查看

**Comment by bober233** [comment]
可以写一个消息通知里的签到吗 大佬

**Comment by LinChiQ** [comment]
我这没有消息通知的签到，你可以自己改一下代码或者联系我有偿改一下，抱歉

**Comment by bober233** [comment]
留个联系方式

**Comment by LinChiQ** [comment]
发邮件到：lateyoung1@gmail.com
